<!--
SPDX-FileCopyrightText: 2026 Neptuwunium

SPDX-License-Identifier: EUPL-1.2
-->

<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Pluto.SourceGen\Pluto.SourceGen.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false"/>
		<ProjectReference Include="..\Charon\Charon.csproj"/>
		<ProjectReference Include="..\Pluto\Pluto.csproj"/>
		<ProjectReference Include="..\Triton\Triton.csproj"/>
		<ProjectReference Include="..\Sedna.Native.SDLShaderCross\Sedna.Native.SDLShaderCross.csproj"/>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="ppy.SDL3-CS" Version="2026.320.0"/>
		<PackageReference Include="Silk.NET.Maths" Version="2.23.0"/>
	</ItemGroup>

</Project>
