<!--
SPDX-FileCopyrightText: 2024-2026 Neptuwunium

SPDX-License-Identifier: EUPL-1.2
-->

<Project>

	<PropertyGroup>
		<Deterministic>true</Deterministic>
		<TargetFrameworks>net10.0;net11.0</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<LangVersion>preview</LangVersion>
		<Nullable>enable</Nullable>
		<Version>1.0.0.0</Version>
		<AssemblyVersion>1.0.0.0</AssemblyVersion>
		<FileVersion>1.0.0.0</FileVersion>
		<ProductVersion>1.0.0.0</ProductVersion>
	</PropertyGroup>

</Project>
