// SPDX-FileCopyrightText: 2024-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

using System;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Pluto.SourceGen;

[Generator]
public class MagicGenerator : IIncrementalGenerator {
	public void Initialize(IncrementalGeneratorInitializationContext context) {
		var source = context.SyntaxProvider.ForAttributeWithMetadataName(
			"Pluto.SourceGen.MagicGenerator.GenerateMagicAttribute",
			static (node, _) => node is RecordDeclarationSyntax,
			static (ctx, _) => (INamedTypeSymbol) ctx.TargetSymbol);

		context.RegisterSourceOutput(source, static (spc, symbol) => {
			var size = (int) symbol.GetAttributes().First(x => x.AttributeClass?.Name == "GenerateMagicAttribute").ConstructorArguments[0].Value!;

			var sb = new StringBuilder();
			sb.AppendLine("/// <auto-generated/>");
			sb.AppendLine();
			sb.AppendLine("using System.Runtime.InteropServices;");
			sb.AppendLine("using System.Globalization;");
			sb.AppendLine();
			sb.AppendLine($"namespace {symbol.ContainingNamespace.ToDisplayString()};");
			sb.AppendLine();
			sb.AppendLine($"[StructLayout(LayoutKind.Explicit, Size = {size})]");

			var type = size switch {
				1 => "byte",
				2 => "ushort",
				4 => "uint",
				8 => "ulong",
				_ => throw new NotSupportedException(),
			};

			sb.AppendLine($"public {(symbol.IsReadOnly ? "readonly " : "")}partial record struct {symbol.Name}([field: FieldOffset(0)] {type} Value) {{");

			sb.AppendLine($"\tpublic static bool operator ==({symbol.Name} left, {type} right) => left.Value == right;");
			sb.AppendLine($"\tpublic static bool operator !=({symbol.Name} left, {type} right) => !(left == right);");
			sb.AppendLine();

			var toString = new StringBuilder();
			toString.AppendLine("\tpublic override string ToString() {");
			toString.AppendLine("\t\tswitch(Value) {");

			foreach (var attribute in symbol.GetAttributes().Where(x => x.AttributeClass?.Name == "MagicAttribute")) {
				var magic = (string) attribute.ConstructorArguments[0].Value!;
				var name = attribute.ConstructorArguments[1].Value ?? magic;
				var isLittleEndian = (bool) attribute.ConstructorArguments[2].Value!;

				var value = 0ul;
				for (var i = 0; i < magic.Length; i++) {
					value |= (ulong) (byte) magic[isLittleEndian ? magic.Length - i - 1 : i] << (i * 8);
				}

				switch (size) {
					case 1 when value > 0xff:
					case 2 when value > 0xffff:
					case 4 when value > 0xffffffff:
						throw new NotSupportedException();
				}

				sb.AppendLine($"\tpublic const {type} {name} = ({type}) 0x{value:x};");
				toString.AppendLine($"\t\t\tcase {name}: return nameof({name});");
			}

			toString.AppendLine($"\t\t\tdefault: return Value.ToString(\"x{size * 2}\", CultureInfo.InvariantCulture);");
			toString.AppendLine("\t\t}");
			toString.AppendLine("\t}");

			sb.AppendLine();
			sb.Append(toString);

			sb.AppendLine("}");
			spc.AddSource($"{symbol.Name}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
		});
	}
}
