// SPDX-FileCopyrightText: 2024-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Pluto.SourceGen;

[Generator]
public class MagicGenerator : IIncrementalGenerator {
	public void Initialize(IncrementalGeneratorInitializationContext context) {
		var source = context.SyntaxProvider.ForAttributeWithMetadataName(
			"Pluto.SourceGen.MagicGenerator.GenerateMagicAttribute",
			static (node, _) => node is ClassDeclarationSyntax,
			static (ctx, _) => (INamedTypeSymbol) ctx.TargetSymbol);

		context.RegisterSourceOutput(source, static (spc, symbol) => {
			var magicAttribute = symbol.GetAttributes().First(x => x.AttributeClass?.Name == "GenerateMagicAttribute");
			var enumName = (string) magicAttribute.ConstructorArguments[0].Value!;
			var size = (int) magicAttribute.ConstructorArguments[1].Value!;
			var altPropName = magicAttribute.ConstructorArguments[2].Value as string;
			var writeAlt = altPropName != null && symbol.IsStatic;

			var sb = new StringBuilder();
			sb.AppendLine("/// <auto-generated/>");
			sb.AppendLine();
			sb.AppendLine("using System.Runtime.InteropServices;");
			sb.AppendLine("using System.Globalization;");
			sb.AppendLine();
			sb.AppendLine($"namespace {symbol.ContainingNamespace.ToDisplayString()};");
			sb.AppendLine();

			var type = size switch {
				1 => "byte",
				2 => "ushort",
				4 => "uint",
				8 => "ulong",
				_ => throw new NotSupportedException(),
			};

			sb.AppendLine($"public enum {enumName} : {type} {{");

			var altString = new StringBuilder();
			if (writeAlt) {
				altString.AppendLine($"\t\tpublic string {altPropName} => value switch {{");
			}

			foreach (var attribute in symbol.GetAttributes().Where(x => x.AttributeClass?.Name == "MagicAttribute")) {
				var magic = (string) attribute.ConstructorArguments[0].Value!;
				var name = attribute.ConstructorArguments[1].Value as string ?? magic;
				var altName = attribute.ConstructorArguments[2].Value as string ?? name;
				var isLittleEndian = (bool) attribute.ConstructorArguments[3].Value!;

				var value = 0ul;
				for (var i = 0; i < magic.Length; i++) {
					value |= (ulong) (byte) magic[isLittleEndian ? magic.Length - i - 1 : i] << (i * 8);
				}

				switch (size) {
					case 1 when value > 0xff:
					case 2 when value > 0xffff:
					case 4 when value > 0xffffffff:
						throw new NotSupportedException();
				}

				sb.AppendLine($"\t{name} = 0x{value:x},");
				if (writeAlt) {
					altString.AppendLine($"\t\t\t{enumName}.{name} => \"{altName}\",");
				}
			}

			sb.AppendLine("}");

			if (writeAlt) {
				altString.AppendLine("\t\t\t_ => value.ToString(),");
				altString.AppendLine("\t\t};");

				sb.AppendLine();
				sb.AppendLine($"public static partial class {symbol.Name} {{");
				sb.AppendLine($"\textension({enumName} value) {{");
				sb.AppendLine(altString.ToString().TrimEnd());
				sb.AppendLine("\t}");
				sb.AppendLine("}");
			}

			spc.AddSource($"{enumName}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
		});
	}
}
