// SPDX-FileCopyrightText: 2024-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Pluto.SourceGen;

[Generator]
public class ReverseEndiannessGenerator : IIncrementalGenerator {
	public void Initialize(IncrementalGeneratorInitializationContext context) {
		var source = context.SyntaxProvider.ForAttributeWithMetadataName(
			"Pluto.SourceGen.ReverseEndiannessGenerator.EndianSwappableAttribute",
			static (node, _) => node switch {
				StructDeclarationSyntax => true,
				RecordDeclarationSyntax record => record.ClassOrStructKeyword.IsKind(SyntaxKind.StructKeyword),
				_ => false,
			},
			static (ctx, _) => (INamedTypeSymbol) ctx.TargetSymbol);

		context.RegisterSourceOutput(source, static (spc, symbol) => {
			var sb = new StringBuilder();
			var name = symbol.ToDisplayString().Substring(symbol.ContainingNamespace.ToDisplayString().Length + 1);

			sb.AppendLine("/// <auto-generated/>");
			sb.AppendLine();
			sb.AppendLine("using System.Buffers.Binary;");
			sb.AppendLine();
			sb.AppendLine($"namespace {symbol.ContainingNamespace.ToDisplayString()};");
			sb.AppendLine();
			sb.AppendLine($"public partial {(symbol.IsRecord ? "record struct" : "struct")} {name} : Pluto.SourceGen.ReverseEndiannessGenerator.IEndianReversible<{name}> {{");

			if (!symbol.GetAttributes().Any(x => x is { AttributeClass: { Name: "TransparentStructAttribute", IsGenericType: true } })) {
				sb.AppendLine($"\tpublic {name} ReverseEndianness() =>");
				sb.AppendLine("\t\tthis with {");

				foreach (var property in symbol.GetMembers().OfType<IPropertySymbol>()) {
					var doNotSwapAttribute = property.GetAttributes().FirstOrDefault(x => x.AttributeClass?.Name == "DoNotSwapAttribute");
					if (doNotSwapAttribute != default) {
						continue;
					}

					if (property.IsStatic) {
						continue;
					}

					var isValueLike = property.Type.IsValueType || property.Type.IsUnmanagedType;
					var isGeneric = property.Type.TypeKind == TypeKind.TypeParameter;

					if (!isValueLike && !isGeneric) {
						sb.AppendLine($"// {property.Name} not a value or type param");
						continue;
					}

					if (isGeneric) {
						var typeParam = symbol.TypeParameters.First(x => x.Name == property.Type.Name);
						if (typeParam.ConstraintTypes.Any(x => x.Name == "IEndianReversible")) {
							sb.AppendLine($"\t\t\t{property.Name} = {property.Name}.ReverseEndianness(),");
						} else if(typeParam.HasUnmanagedTypeConstraint || typeParam.HasValueTypeConstraint) {
							sb.AppendLine($"\t\t\t{property.Name} = Pluto.Helpers.ReverseStruct<{property.Type.ToDisplayString()}, {property.Type.ToDisplayString()}>({property.Name}),");
						}

						continue;
					}

					if (property.Type is INamedTypeSymbol { IsGenericType: true } propertyType) {
						var hasFunc = property.Type.GetMembers().OfType<IMethodSymbol>().Any(x => x is { Name: "ReverseEndianness", Parameters.Length: 0 });

						if (!hasFunc) {
							hasFunc = propertyType.Interfaces.Any(x => x.Name == "IEndianReversible");
						}

						if (!hasFunc) {
							hasFunc = propertyType.GetAttributes().Any(x => x.AttributeClass?.Name == "EndianSwappableAttribute");
						}

						if (hasFunc) {
							sb.AppendLine($"\t\t\t{property.Name} = {property.Name}.ReverseEndianness(),");
						} else if(propertyType.TypeParameters.Length == 1) {
							sb.AppendLine($"\t\t\t{property.Name} = Pluto.Helpers.ReverseStruct<{propertyType.ToDisplayString()}, {propertyType.TypeParameters[0].ToDisplayString()}>({property.Name}),");
						}
					}

					switch (property.Type.Name) {
						case "Byte":
						case "Boolean":
						case "SByte":
							break;
						case "Int16":
						case "UInt16":
						case "Int32":
						case "UInt32":
						case "Int64":
						case "UInt64":
						case "Single":
						case "Double":
							sb.AppendLine($"\t\t\t{property.Name} = BinaryPrimitives.ReverseEndianness({property.Name}),");
							break;
						default: {
							if (property.Type is INamedTypeSymbol { EnumUnderlyingType: { } enumType }) {
								if (enumType.Name is not ("Byte" or "Boolean" or "SByte")) {
									sb.AppendLine($"\t\t\t{property.Name} = ({property.Type.ToDisplayString()}) BinaryPrimitives.ReverseEndianness(({enumType.ToDisplayString()}) {property.Name}),");
								}

								break;
							}

							var hasFunc = property.Type.GetMembers().OfType<IMethodSymbol>().Any(x => x is { Name: "ReverseEndianness", Parameters.Length: 0 });
							if (!hasFunc) {
								hasFunc = property.Type.GetAttributes().Any(x => x.AttributeClass?.Name == "EndianSwappableAttribute");
							}

							if (hasFunc) {
								sb.AppendLine($"\t\t\t{property.Name} = {property.Name}.ReverseEndianness(),");
							}

							break;
						}
					}
				}

				sb.AppendLine("\t\t};");
			}

			sb.AppendLine("}");
			spc.AddSource($"{symbol.Name}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
		});
	}
}
