// SPDX-FileCopyrightText: 2024-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Pluto.SourceGen;

[Generator]
public class ReverseEndiannessGenerator : IIncrementalGenerator {
	public void Initialize(IncrementalGeneratorInitializationContext context) {
		var source = context.SyntaxProvider.ForAttributeWithMetadataName(
			"Pluto.SourceGen.ReverseEndiannessGenerator.EndianSwappableAttribute",
			static (node, _) => node switch {
				StructDeclarationSyntax => true,
				RecordDeclarationSyntax record => record.ClassOrStructKeyword.IsKind(SyntaxKind.StructKeyword),
				_ => false,
			},
			static (ctx, _) => (INamedTypeSymbol) ctx.TargetSymbol);

		context.RegisterSourceOutput(source, static (spc, symbol) => {
			var sb = new StringBuilder();
			sb.AppendLine("/// <auto-generated/>");
			sb.AppendLine();
			sb.AppendLine("using System.Buffers.Binary;");
			sb.AppendLine();
			sb.AppendLine($"namespace {symbol.ContainingNamespace.ToDisplayString()};");
			sb.AppendLine();
			sb.AppendLine($"public partial {(symbol.IsRecord ? "record struct" : "struct")} {symbol.Name} : Pluto.SourceGen.ReverseEndiannessGenerator.IEndianReversible<{symbol.Name}> {{");

			if (!symbol.GetAttributes().Any(x => x is { AttributeClass: { Name: "TransparentStructAttribute", IsGenericType: true } })) {
				sb.AppendLine($"\tpublic {symbol.Name} ReverseEndianness() =>");
				sb.AppendLine("\t\tthis with {");

				foreach (var property in symbol.GetMembers().OfType<IPropertySymbol>()) {
					var doNotSwapAttribute = property.GetAttributes().FirstOrDefault(x => x.AttributeClass?.Name == "DoNotSwapAttribute");
					if (doNotSwapAttribute != default) {
						continue;
					}

					if (property.IsStatic) {
						continue;
					}

					if (!property.Type.IsValueType) {
						continue;
					}

					switch (property.Type.Name) {
						case "Byte":
						case "Boolean":
						case "SByte":
							break;
						case "Int16":
						case "UInt16":
						case "Int32":
						case "UInt32":
						case "Int64":
						case "UInt64":
						case "Single":
						case "Double":
							sb.AppendLine($"\t\t\t{property.Name} = BinaryPrimitives.ReverseEndianness({property.Name}),");
							break;
						default: {
							if (property.Type is INamedTypeSymbol { EnumUnderlyingType: { } enumType }) {
								if (enumType.Name is not ("Byte" or "Boolean" or "SByte")) {
									sb.AppendLine($"\t\t\t{property.Name} = ({property.Type.Name}) BinaryPrimitives.ReverseEndianness(({enumType.ToDisplayString()}) {property.Name}),");
								}

								break;
							}

							var hasFunc = property.Type.GetMembers().OfType<IMethodSymbol>().Any(x => x.Name == "ReverseEndianness" && x.Parameters.Length == 0);
							if (!hasFunc) {
								hasFunc = property.Type.GetAttributes().Any(x => x.AttributeClass?.Name == "EndianSwappableAttribute");
							}

							if (hasFunc) {
								sb.AppendLine($"\t\t\t{property.Name} = {property.Name}.ReverseEndianness(),");
							}

							break;
						}
					}
				}

				sb.AppendLine("\t\t};");
			}

			sb.AppendLine("}");
			spc.AddSource($"{symbol.Name}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
		});
	}
}
