// SPDX-FileCopyrightText: 2024-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Pluto.SourceGen;

[Generator]
public class ReverseEndiannessGenerator : IIncrementalGenerator {
	public void Initialize(IncrementalGeneratorInitializationContext context) {
		var source = context.SyntaxProvider.ForAttributeWithMetadataName(
			"Pluto.SourceGen.ReverseEndiannessGenerator.EndianSwappableAttribute",
			static (node, _) => node is StructDeclarationSyntax,
			static (ctx, _) => (INamedTypeSymbol) ctx.TargetSymbol);

		context.RegisterSourceOutput(source, static (spc, symbol) => {
			var sb = new StringBuilder();
			sb.AppendLine("/// <auto-generated/>");
			sb.AppendLine();
			sb.AppendLine("using System.Buffers.Binary;");
			sb.AppendLine();
			sb.AppendLine($"namespace {symbol.ContainingNamespace.ToDisplayString()};");
			sb.AppendLine();
			sb.AppendLine($"public static partial struct {symbol.Name} {{");

			sb.AppendLine($"\tpublic {symbol.Name} ReverseEndianness() {{");

			sb.AppendLine("\t\treturn this with {");

			foreach (var property in symbol.GetMembers().OfType<IPropertySymbol>()) {
				var doNotSwapAttribute = property.GetAttributes().FirstOrDefault(x => x.AttributeClass?.Name == "DoNotSwapAttribute");
				if (doNotSwapAttribute != default) {
					continue;
				}

				if (property.IsStatic) {
					continue;
				}

				if (!property.Type.IsValueType) {
					continue;
				}

				switch (property.Type.Name) {
					case "Int16":
					case "UInt16":
					case "Int32":
					case "UInt32":
					case "Int64":
					case "UInt64":
					case "Single":
					case "Double":
						sb.AppendLine($"\t\t\t{property.Name} = BinaryPrimitives.ReverseEndianness({property.Name}),");
						break;
					default:
						sb.AppendLine($"\t\t\t{property.Name} = {property.Name}.ReverseEndianness(),");
						break;
				}
			}

			sb.AppendLine("\t\t};");
			sb.AppendLine("\t}");
			sb.AppendLine("}");
			spc.AddSource($"{symbol.Name}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
		});
	}
}
