// SPDX-FileCopyrightText: 2024-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Pluto.SourceGen;

[Generator]
public class TransparentStructGenerator : IIncrementalGenerator {
	public void Initialize(IncrementalGeneratorInitializationContext context) {
		var source = context.SyntaxProvider.ForAttributeWithMetadataName(
			"Pluto.SourceGen.TransparentStructGenerator.TransparentStructAttribute`1",
			static (node, _) => node is StructDeclarationSyntax,
			static (ctx, _) => (INamedTypeSymbol) ctx.TargetSymbol);

		context.RegisterSourceOutput(source, static (spc, symbol) => {
			var typeAttribute = symbol.GetAttributes().First(x => x is { AttributeClass: { Name: "TransparentStructAttribute", IsGenericType: true } });
			var label = (string) (typeAttribute.ConstructorArguments[0].Value ?? "Value");
			var type = typeAttribute.AttributeClass!.TypeArguments[0].ToDisplayString();
			var name = symbol.Name;
			
			var sb = new StringBuilder();sb.AppendLine("/// <auto-generated/>");
			sb.AppendLine();
			sb.AppendLine("#nullable enable");
			sb.AppendLine();
			sb.AppendLine("using System.Diagnostics.CodeAnalysis;");
			sb.AppendLine();
			sb.AppendLine($"namespace {symbol.ContainingNamespace.ToDisplayString()};");
			sb.AppendLine();
			sb.AppendLine($"public partial struct {name} : IEquatable<{name}>, IEquatable<{type}>, IComparable<{name}>, IComparable<{type}> {{");
			sb.AppendLine($"\tpublic {type} {label} {{ get; set; }}");
			sb.AppendLine($"\tpublic {name}({type} value) => this.{label} = value;");
			sb.AppendLine($"\tpublic bool Equals({name} other) => other.{label} == this.{label};");
			sb.AppendLine($"\tpublic bool Equals({type} other) => other == this.{label};");
			sb.AppendLine($"\tpublic int CompareTo({name} other) => this.{label}.CompareTo(other.{label});");
			sb.AppendLine($"\tpublic int CompareTo({type} other) => this.{label}.CompareTo(other);");
			sb.AppendLine($"\tpublic override bool Equals([NotNullWhen(true)] object? obj) => obj switch {{ {name} {name} => this.Equals({name}), {type} other => this.Equals(other), _ => false }};");
			sb.AppendLine($"\tpublic override int GetHashCode() => this.{label}.GetHashCode();");
			sb.AppendLine($"\tpublic override string ToString() => this.{label}.ToString();");
			sb.AppendLine($"\tpublic static bool operator ==({name} left, {name} right) => left.Equals(right);");
			sb.AppendLine($"\tpublic static bool operator !=({name} left, {name} right) => !(left == right);");
			sb.AppendLine($"\tpublic static bool operator ==({name} left, {type} right) => left.Equals(right);");
			sb.AppendLine($"\tpublic static bool operator !=({name} left, {type} right) => !(left == right);");
			sb.AppendLine($"\tpublic static implicit operator {name}({type} value) => new(value);");
			sb.AppendLine($"\tpublic static implicit operator {type}({name} value) => value.{label};");
			sb.AppendLine("}");
			sb.AppendLine();
			spc.AddSource($"{name}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
		});
	}
}
