// SPDX-FileCopyrightText: 2024-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Pluto.SourceGen;

[Generator]
public class TransparentStructGenerator : IIncrementalGenerator {
	public void Initialize(IncrementalGeneratorInitializationContext context) {
		var source = context.SyntaxProvider.ForAttributeWithMetadataName(
			"Pluto.SourceGen.TransparentStructGenerator.TransparentStructAttribute`1",
			static (node, _) => node is StructDeclarationSyntax,
			static (ctx, _) => (INamedTypeSymbol) ctx.TargetSymbol);

		var combined = source.Combine(context.CompilationProvider.Select((compilation, _) => compilation.GetTypeByMetadataName("System.Object")));
		
		context.RegisterSourceOutput(combined, static (spc, provider) => {
			var symbol = provider.Left;
			var objectType = provider.Right;
			var typeAttribute = symbol.GetAttributes().First(x => x is { AttributeClass: { Name: "TransparentStructAttribute", IsGenericType: true } });
			var label = (string) (typeAttribute.ConstructorArguments[0].Value ?? "Value");
			var valueType = typeAttribute.AttributeClass!.TypeArguments[0];
			var type = valueType.ToDisplayString();
			var name = symbol.Name;

			var hasConstructor = false;
			var hasEqualsSelf = false;
			var hasEqualsValue = false;
			var hasEqualsObject = false;
			var hasCompareSelf = false;
			var hasCompareValue = false;
			var hasHashCode = false;
			var hasToString = false;
			var cmp = SymbolEqualityComparer.Default;
			foreach (var member in symbol.GetMembers()) {
				if (member is not { Kind: SymbolKind.Method }) {
					continue;
				}

				if (member is not IMethodSymbol method) {
					continue;
				}

				if (method.IsStatic) {
					continue;
				}

				if (method.MethodKind == MethodKind.Constructor) {
					hasConstructor = method.Parameters.Length == 1 && cmp.Equals(method.Parameters[0].Type, valueType);
					continue;
				}

				if (method.MethodKind != MethodKind.Ordinary) {
					continue;
				}

				switch (method.Name) {
					case "Equals": {
						if (method.Parameters.Length != 1) {
							continue;
						}

						if (cmp.Equals(method.Parameters[0].Type, symbol)) {
							hasEqualsSelf = true;
						}
				
						if (cmp.Equals(method.Parameters[0].Type, valueType)) {
							hasEqualsValue = true;
						}
				
						if (cmp.Equals(method.Parameters[0].Type, objectType)) {
							hasEqualsObject = true;
						}

						break;
					}
					case "Compare": {
						if (method.Parameters.Length != 1) {
							continue;
						}

						if (cmp.Equals(method.Parameters[0].Type, symbol)) {
							hasCompareSelf = true;
						}
				
						if (cmp.Equals(method.Parameters[0].Type, valueType)) {
							hasCompareValue = true;
						}

						break;
					}
					case "ToString": {
						if (method.Parameters.Length != 0) {
							continue;
						}

						hasToString = true;
						break;
					}
					case "GetHashCode": {
						if (method.Parameters.Length != 0) {
							continue;
						}

						hasHashCode = true;
						break;
					}
				}
			}

			var sb = new StringBuilder();
			sb.AppendLine("/// <auto-generated/>");
			sb.AppendLine();
			sb.AppendLine("#nullable enable");
			sb.AppendLine();
			sb.AppendLine("using System.Diagnostics.CodeAnalysis;");
			sb.AppendLine();
			sb.AppendLine($"namespace {symbol.ContainingNamespace.ToDisplayString()};");
			sb.AppendLine();
			sb.AppendLine($"public partial struct {name} : IEquatable<{name}>, IEquatable<{type}>, IComparable<{name}>, IComparable<{type}> {{");
			sb.AppendLine($"\tpublic {type} {label} {{ get; set; }}");
			
			if (!hasConstructor) {
				sb.AppendLine($"\tpublic {name}({type} value) => this.{label} = value;");
			}

			if (!hasEqualsSelf) {
				sb.AppendLine($"\tpublic bool Equals({name} other) => other.{label} == this.{label};");
			}

			if (!hasEqualsValue) {
				sb.AppendLine($"\tpublic bool Equals({type} other) => other == this.{label};");
			}

			if (!hasCompareSelf) {
				sb.AppendLine($"\tpublic int CompareTo({name} other) => this.{label}.CompareTo(other.{label});");
			}

			if (!hasCompareValue) {
				sb.AppendLine($"\tpublic int CompareTo({type} other) => this.{label}.CompareTo(other);");
			}

			if (!hasEqualsObject) {
				sb.AppendLine($"\tpublic override bool Equals([NotNullWhen(true)] object? obj) => obj switch {{ {name} {name} => this.Equals({name}), {type} other => this.Equals(other), _ => false }};");
			}

			if (!hasHashCode) {
				sb.AppendLine($"\tpublic override int GetHashCode() => this.{label}.GetHashCode();");
			}

			if (!hasToString) {
				sb.AppendLine($"\tpublic override string ToString() => this.{label}.ToString();");
			}

			sb.AppendLine($"\tpublic static bool operator ==({name} left, {name} right) => left.Equals(right);");
			sb.AppendLine($"\tpublic static bool operator !=({name} left, {name} right) => !(left == right);");
			sb.AppendLine($"\tpublic static implicit operator {name}({type} value) => new(value);");
			sb.AppendLine($"\tpublic static implicit operator {type}({name} value) => value.{label};");
			sb.AppendLine("}");
			sb.AppendLine();
			spc.AddSource($"{name}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
		});
	}
}
