# SPDX-FileCopyrightText: 2023-2026 Neptuwunium
#
# SPDX-License-Identifier: CC0-1.0

FROM docker.io/debian:trixie
WORKDIR /app
RUN apt-get update && \
	apt-get install -y build-essential cmake mingw-w64 curl gcc-mingw-w64-ucrt64 g++-mingw-w64-ucrt64

ENV CC=x86_64-w64-mingw32ucrt-gcc
ENV CXX=x86_64-w64-mingw32ucrt-g++
ENV AR=x86_64-w64-mingw32-ar
ENV RANLIB=x86_64-w64-mingw32-ranlib
ENV STRIP=x86_64-w64-mingw32-strip
ENV CFLAGS="-static -static-libgcc"
ENV CXXFLAGS="-static -static-libgcc -static-libstdc++"
ENV DLLTOOL=x86_64-w64-mingw32-dlltool 

# specific layers
ENV VERSION=1.10.0
RUN curl https://github.com/lz4/lz4/releases/download/v${VERSION}/lz4-${VERSION}.tar.gz --location | tar xzvf - && \
	cd lz4-${VERSION} && \
	make -j$(nproc) -C lib OS=Windows_NT && \
	make -C lib install PREFIX=/app/out OS=Windows_NT
