FROM docker.io/debian:trixie
WORKDIR /app
RUN apt-get update && \
	apt-get install -y build-essential cmake mingw-w64 curl

ENV CC=x86_64-w64-mingw32-gcc
ENV CXX=x86_64-w64-mingw32-g++
ENV AR=x86_64-w64-mingw32-ar
ENV RANLIB=x86_64-w64-mingw32-ranlib
ENV STRIP=x86_64-w64-mingw32-strip
ENV CFLAGS="-static-libgcc"

# specific layers
COPY . .

ENV ZLIB_VERSION=1.3.1
ENV PNG_VERSION=1.6.50

RUN curl https://zlib.net/zlib-${ZLIB_VERSION}.tar.gz --location | tar xzvf - && \
	cd zlib-${ZLIB_VERSION} && \
	mkdir build && cd build && \
	cmake .. -DCMAKE_SYSTEM_NAME=Windows -DCMAKE_C_COMPILER=${CC} -DCMAKE_C_FLAGS="${CFLAGS}" \
		-DCMAKE_FIND_ROOT_PATH=/usr/x86_64-w64-mingw32,/app/out \
		-DCMAKE_RC_COMPILER=x86_64-w64-mingw32-windres -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=/app/out && \
	make -j$(nproc) && make install && \
	cd /app

RUN curl https://download.sourceforge.net/libpng/libpng-${PNG_VERSION}.tar.gz --location | tar xzvf - && \
	cd libpng-${PNG_VERSION} && \
	mkdir build && cd build && \
	cmake .. -DCMAKE_SYSTEM_NAME=Windows -DCMAKE_C_COMPILER=${CC} -DCMAKE_C_FLAGS="${CFLAGS}" \
		-DZLIB_INCLUDE_DIR=/app/out/include -DCMAKE_FIND_ROOT_PATH=/usr/x86_64-w64-mingw32,/app/out \
		-DPNG_TOOLS=OFF -DPNG_TESTS=OFF \
		-DCMAKE_RC_COMPILER=x86_64-w64-mingw32-windres -DPNG_SHARED=ON -DCMAKE_INSTALL_PREFIX=/app/out && \
	make -j$(nproc) && make install
