# SPDX-FileCopyrightText: 2026 Neptuwunium
#
# SPDX-License-Identifier: CC0-1.0

FROM docker.io/debian:trixie
WORKDIR /app
RUN apt-get update && \
	apt-get install -y build-essential cmake mingw-w64 gcc-mingw-w64-ucrt64 g++-mingw-w64-ucrt64 python3

ENV CC=x86_64-w64-mingw32ucrt-gcc
ENV CXX=x86_64-w64-mingw32ucrt-g++
ENV AR=x86_64-w64-mingw32-ar
ENV RANLIB=x86_64-w64-mingw32-ranlib
ENV STRIP=x86_64-w64-mingw32-strip
ENV CFLAGS="-static -static-libgcc"
ENV CXXFLAGS="-static -static-libgcc -static-libstdc++"

# specific layers
COPY SDL SDL
RUN cmake -B build-SDL \
	-DCMAKE_SYSTEM_NAME=Windows \
	-DCMAKE_C_COMPILER="${CC}" \
	-DCMAKE_CXX_COMPILER="${CXX}" \
	-DCMAKE_C_FLAGS="${CFLAGS}" \
	-DCMAKE_CXX_FLAGS="${CXXFLAGS}" \
	-DCMAKE_FIND_ROOT_PATH=/usr/x86_64-w64-mingw32,/app/out \
	-DCMAKE_RC_COMPILER=x86_64-w64-mingw32-windres \
	-DBUILD_SHARED_LIBS=ON \
	-DCMAKE_INSTALL_PREFIX=/app/out \
	SDL && \
	cmake --build build-SDL --parallel $(nproc) && \
	cmake --install build-SDL

COPY SDL_shadercross SDL_shadercross
RUN cmake -B build-SDL_shadercross \
	-DCMAKE_SYSTEM_NAME=Windows \
	-DCMAKE_C_COMPILER="${CC}" \
	-DCMAKE_CXX_COMPILER="${CXX}" \
	-DCMAKE_C_FLAGS="${CFLAGS}" \
	-DCMAKE_CXX_FLAGS="${CXXFLAGS}" \
	-DCMAKE_FIND_ROOT_PATH=/usr/x86_64-w64-mingw32,/app/out \
	-DCMAKE_RC_COMPILER=x86_64-w64-mingw32-windres \
	-DBUILD_SHARED_LIBS=ON \
	-DCMAKE_PREFIX_PATH=/app/out \
	-DSDL3_DIR=/app/out/lib/cmake/SDL3 \
	-DSDLSHADERCROSS_DXC=OFF \
	-DSDLSHADERCROSS_VENDORED=ON \
	-DSDLSHADERCROSS_INSTALL=ON \
	-DSDLSHADERCROSS_INSTALL_RUNTIME=ON \
	-DCMAKE_INSTALL_PREFIX=/app/out \
	SDL_shadercross && \
	cmake --build build-SDL_shadercross --parallel $(nproc) && \
	cmake --install build-SDL_shadercross

# DXC is theoretically possible if we pull in DirectX-Headers (for d3d12.h), dxvk (for dxgi.lib), and vkd3d (for d3d12.lib)
