<!--
SPDX-FileCopyrightText: 2025 Legiayayana

SPDX-License-Identifier: EUPL-1.2 OR LGPL-3.0-or-later
You may choose either license when using or modifying this code.
-->

<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<LangVersion>preview</LangVersion>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>

</Project>
